-- =====================================================================
-- CAT & DOG PET SHOP - catalogo digital - banco completo
--
-- Rode este arquivo INTEIRO no Supabase do cliente:
--   SQL Editor > New query > cole tudo > Run
--
-- Cria tudo do zero, num projeto Supabase novo e vazio. Pode rodar de
-- novo sem quebrar nada (e idempotente).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Usuarios do painel administrativo
-- ---------------------------------------------------------------------
create table if not exists public.users (
  id         bigint generated by default as identity primary key,
  nome       text        not null,
  login      text        not null unique,
  senha_hash text        not null,
  role       text        not null default 'operador',   -- admin | operador
  ativo      boolean     not null default true,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 2. Produtos do catalogo
--
-- Um produto pode ser vendido de tres formas, e o painel liga cada uma:
--   saco fechado  -> preco_saco_fechado + peso_saco_kg   (estoque em kg)
--   fracionado    -> preco_por_kg                        (estoque em kg)
--   por unidade   -> preco_unitario                      (estoque em un)
-- ---------------------------------------------------------------------
create table if not exists public.products (
  id                bigint generated by default as identity primary key,
  nome              text          not null,
  marca             text          default '',
  categoria         text          not null default 'racao',
  descricao         text,

  -- como aparece e como filtra no catalogo
  especie           text,          -- cao | gato | null (serve os dois)
  porte             text,          -- pequena | media | grande | null
  perfil            text,          -- filhote | adulto | castrado | senior | null
  foto_url          text,
  visivel_loja      boolean       not null default true,
  vende_fracionado  boolean       not null default true,

  -- precos
  peso_saco_kg      numeric(10,3) not null default 0,
  preco_saco_fechado numeric(10,2) not null default 0,
  preco_por_kg      numeric(10,4) not null default 0,
  preco_unitario    numeric(10,2) not null default 0,
  custo             numeric(10,2) not null default 0,

  -- estoque
  estoque_kg        numeric(10,3) not null default 0,
  estoque_unidade   integer       not null default 0,
  estoque_minimo    numeric(10,3) not null default 0,

  ativo             integer       not null default 1,
  created_at        timestamptz   not null default now(),
  updated_at        timestamptz   not null default now()
);

create index if not exists products_ativo_idx    on public.products (ativo);
create index if not exists products_especie_idx  on public.products (especie);
create index if not exists products_categoria_idx on public.products (categoria);

-- ---------------------------------------------------------------------
-- 3. Clientes (criados sozinhos no primeiro pedido, pelo WhatsApp)
-- ---------------------------------------------------------------------
create table if not exists public.clients (
  id             bigint generated by default as identity primary key,
  nome           text not null,
  whatsapp       text not null,
  endereco       text,
  referencia     text,
  observacao     text,
  ultimo_pedido  timestamptz,
  created_at     timestamptz not null default now()
);

create unique index if not exists clients_whatsapp_idx on public.clients (whatsapp);

-- ---------------------------------------------------------------------
-- 4. Pedidos
-- ---------------------------------------------------------------------
create table if not exists public.orders (
  id               bigint generated by default as identity primary key,
  client_id        bigint references public.clients(id) on delete set null,
  cliente_nome     text        not null,
  cliente_whatsapp text        not null,
  tipo_entrega     text        not null default 'entrega',  -- entrega | retirada
  endereco         text,
  referencia       text,
  janela           text,                                    -- "Hoje, 14h as 17h"
  observacao       text,
  subtotal         numeric(10,2) not null default 0,
  frete            numeric(10,2) not null default 0,
  total            numeric(10,2) not null default 0,
  status           text        not null default 'novo',
  -- novo | confirmado | separando | pronto | entregue | cancelado
  forma_pagamento  text,                                    -- dinheiro | pix | cartao
  assinatura       boolean     not null default false,
  frequencia       text,                                    -- semanal | quinzenal | mensal
  baixou_estoque   boolean     not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- quantidade_kg guarda a quantidade na unidade do tipo_venda:
--   'kg'      -> quilos
--   'saco'    -> numero de sacos fechados
--   'unidade' -> numero de unidades
create table if not exists public.order_items (
  id             bigint generated by default as identity primary key,
  order_id       bigint not null references public.orders(id) on delete cascade,
  product_id     bigint references public.products(id) on delete set null,
  descricao      text   not null,
  tipo_venda     text   not null default 'kg',
  quantidade_kg  numeric(10,3) not null default 0,
  preco_unitario numeric(10,4) not null default 0,
  subtotal       numeric(10,2) not null default 0
);

create index if not exists orders_status_idx     on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_whatsapp_idx   on public.orders (cliente_whatsapp);
create index if not exists order_items_order_idx on public.order_items (order_id);
create index if not exists order_items_prod_idx  on public.order_items (product_id);

-- ---------------------------------------------------------------------
-- 5. Movimentacoes de estoque (historico de entrada e saida)
-- ---------------------------------------------------------------------
create table if not exists public.stock_movements (
  id            bigint generated by default as identity primary key,
  product_id    bigint references public.products(id) on delete cascade,
  tipo          text not null,                  -- entrada | saida | ajuste
  quantidade_kg numeric(10,3) not null default 0,
  quantidade_un integer not null default 0,
  motivo        text,
  order_id      bigint references public.orders(id) on delete set null,
  created_at    timestamptz not null default now()
);

create index if not exists stock_prod_idx on public.stock_movements (product_id);

-- ---------------------------------------------------------------------
-- 6. Configuracoes da loja (chave/valor)
-- ---------------------------------------------------------------------
create table if not exists public.settings (
  key   text primary key,
  value text
);

insert into public.settings (key, value) values
  ('nome_loja',          'Cat & Dog Pet Shop'),
  ('loja_aberta',        'true'),
  ('whatsapp_loja',      ''),
  ('endereco_loja',      'Av. Abilio Augusto Tavora, 2429'),
  ('email_loja',         'petshopcatedog07@gmail.com'),
  ('cnpj_loja',          '08.659.314/0001-02'),
  ('frete_valor',        '9.90'),
  ('frete_gratis_acima', '99'),
  ('pedido_minimo',      '0')
on conflict (key) do nothing;

-- ---------------------------------------------------------------------
-- 7. Balde de arquivos para as fotos dos produtos
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('produtos', 'produtos', true, 3145728,
        array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update
  set public = true,
      file_size_limit = 3145728,
      allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp'];

drop policy if exists produtos_leitura on storage.objects;
drop policy if exists produtos_envio   on storage.objects;
drop policy if exists produtos_troca   on storage.objects;
drop policy if exists produtos_remocao on storage.objects;

create policy produtos_leitura on storage.objects
  for select to anon, authenticated using (bucket_id = 'produtos');
create policy produtos_envio on storage.objects
  for insert to anon, authenticated with check (bucket_id = 'produtos');
create policy produtos_troca on storage.objects
  for update to anon, authenticated using (bucket_id = 'produtos') with check (bucket_id = 'produtos');
create policy produtos_remocao on storage.objects
  for delete to anon, authenticated using (bucket_id = 'produtos');

-- ---------------------------------------------------------------------
-- 8. Acesso as tabelas
--
-- A chave anon (publica, que fica no navegador) precisa ler o catalogo e
-- gravar pedido. O resto passa pela API, que roda no servidor.
--
-- COMO FECHAR DE VERDADE (recomendado antes de crescer): coloque a
-- SUPABASE_SERVICE_ROLE_KEY nas variaveis da Vercel. A API ja usa ela
-- quando existe, e ai voce pode apagar as policies de leitura de orders,
-- clients e users, deixando o anon so com o catalogo e o INSERT de pedido.
-- ---------------------------------------------------------------------
alter table public.products        enable row level security;
alter table public.orders          enable row level security;
alter table public.order_items     enable row level security;
alter table public.clients         enable row level security;
alter table public.settings        enable row level security;
alter table public.users           enable row level security;
alter table public.stock_movements enable row level security;

do $$
declare t text;
begin
  foreach t in array array['products','orders','order_items','clients','settings','users','stock_movements']
  loop
    execute format('drop policy if exists %I_tudo on public.%I', t, t);
    execute format(
      'create policy %I_tudo on public.%I for all to anon, authenticated using (true) with check (true)',
      t, t);
  end loop;
end $$;

-- ---------------------------------------------------------------------
-- 9. Primeiro acesso ao painel
--
-- Deixe como esta e crie o usuario pela propria tela de primeiro acesso
-- em /admin - ela so aparece enquanto a tabela users estiver vazia, e a
-- senha e gravada com salt (scrypt) pela API.
-- ---------------------------------------------------------------------
